apiVersion: v1
kind: Secret
metadata:
  name: {{ template "beskar-yum.fullname" . }}-secret
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "beskar-yum.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if eq .Values.configData.storage.driver "azure" }}
    {{- if and .Values.secrets.azure.accountName .Values.secrets.azure.accountKey .Values.secrets.azure.container }}
  azureAccountName: {{ .Values.secrets.azure.accountName | b64enc | quote }}
  azureAccountKey: {{ .Values.secrets.azure.accountKey | b64enc | quote }}
    {{- end }}
  {{- else if eq .Values.configData.storage.driver "s3" }}
    {{- if and .Values.secrets.s3.secretKey .Values.secrets.s3.accessKey }}
  s3AccessKey: {{ .Values.secrets.s3.accessKey | b64enc | quote }}
  s3SecretKey: {{ .Values.secrets.s3.secretKey | b64enc | quote }}
    {{- end }}
  {{- else if eq .Values.configData.storage.driver "gcs" }}
  gcsKeyfile: {{ .Values.secrets.gcs.keyfile | b64enc | quote }}
  {{- end }}
  registryUsername: {{ .Values.secrets.registry.username | b64enc | quote }}
  registryPassword: {{ .Values.secrets.registry.password | b64enc | quote }}